name: Set up uv
description: Install uv and Python and, if desired, dependencies
inputs:
  install-and-cache-dependencies:
    default: "false"
    description: whether to install the dependencies specified in pyproject.toml
    required: true
  python-version:
    description: Python version to be installed
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: fromJSON(inputs.install-and-cache-dependencies)
        python-version: ${{ inputs.python-version }}
    - if: fromJSON(inputs.install-and-cache-dependencies)
      run: uv sync --locked
      shell: bash
